/* Saved 3:24 PM 10/23/2008 from url="http://simple.wiktionary.org/wiki/Wiktionary:Academic_word_list"

All content available under the GNU Free Documentation License.  For text of this License, see "http://www.gnu.org/copyleft/fdl.html".

The Academic Word List (AWL) was developed by Averil Coxhead at the School of Linguistics and Applied Language Studies at Victoria University of Wellington, New Zealand. The list contains 570 word families which were selected because they appear with great frequency in a broad range of academic texts. The list does not include words that are in the most frequent 2000 words of English (the General Service List), thus making it specific to academic contexts. The AWL was primarily made so that it could be used by teachers as part of a programme preparing learners for tertiary level study or used by students working alone to learn the words most needed to study at colleges and universities.

The 570 words are divided into 10 sublists. The sublists are ordered such that the words in the first sublist are the most frequent words and those in the last sublist are the least frequent.
*/

var frequent = new Array(
"sector", "available", "financial", "process", "individual", "specific", "principle", "estimate", "variables", "method", "data", "research", "contract", "environment", "export", "source", "assessment", "policy", "identified", "create", "derived", "factors", "procedure", "definition", "assume", "theory", "benefit", "evidence", "established", "authority", "major", "issues", "labour", "occur", "economic", "involved", "percent", "interpretation", "consistent", "income", "structure", "legal", "concept", "formula", "section", "required", "constitutional", "analysis", "distribution", "function", "area", "approach", "role", "legislation", "indicate", "response", "period", "context", "significant", "similar",

"community", "resident", "range", "construction", "strategies", "elements", "previous", "conclusion", "security", "aspects", "acquisition", "features", "text", "commission", "regulations", "computer", "items", "consumer", "achieve", "final", "positive", "evaluation", "assistance", "normal", "relevant", "distinction", "region", "traditional", "impact", "consequences", "chapter", "equation", "appropriate", "resources", "participation", "survey", "potential", "cultural", "transfer", "select", "credit", "affect", "categories", "perceived", "sought", "focus", "purchase", "injury", "site", "journal", "primary", "complex", "institute", "investment", "administration", "maintenance", "design", "obtained", "restricted", "conduct",

"comments", "convention", "published", "framework", "implies", "negative", "dominant", "illustrated", "outcomes", "constant", "shift", "deduction", "ensure", "specified", "justification", "funds", "reliance", "physical", "partnership", "location", "link", "coordination", "alternative", "initial", "validity", "task", "techniques", "excluded", "consent", "proportion", "demonstrate", "reaction", "criteria", "minorities", "technology", "philosophy", "removed", "sex", "compensation", "sequence", "corresponding", "maximum", "circumstances", "instance", "considerable", "sufficient", "corporate", "interaction", "contribution", "immigration", "component", "constraints", "technical", "emphasis", "scheme", "layer", "volume", "document", "registered", "core",

"overall", "emerged", "regime", "implementation", "project", "hence", "occupational", "internal", "goals", "retained", "sum", "integration", "mechanism", "parallel", "imposed", "despite", "job", "parameters", "approximate", "label", "concentration", "principal", "series", "predicted", "summary", "attitudes", "undertaken", "cycle", "communication", "ethnic", "hypothesis", "professional", "status", "conference", "attributed", "annual", "obvious", "error", "implications", "apparent", "commitment", "subsequent", "debate", "dimensions", "promote", "statistics", "option", "domestic", "output", "access", "code", "investigation", "phase", "prior", "granted", "stress", "civil", "contrast", "resolution", "adequate",

"alter", "stability", "energy", "aware", "licence", "enforcement", "draft", "styles", "precise", "medical", "pursue", "symbolic", "marginal", "capacity", "generation", "exposure", "decline", "academic", "modified", "external", "psychology", "fundamental", "adjustment", "ratio", "whereas", "enable", "version", "perspective", "contact", "network", "facilitate", "welfare", "transition", "amendment", "logic", "rejected", "expansion", "clause", "prime", "target", "objective", "sustainable", "equivalent", "liberal", "notion", "substitution", "generated", "trend", "revenue", "compounds", "evolution", "conflict", "image", "discretion", "entities", "orientation", "consultation", "mental", "monitoring", "challenge",

"intelligence", "transformation", "presumption", "acknowledged", "utility", "furthermore", "accurate", "diversity", "attached", "recovery", "assigned", "tapes", "motivation", "bond", "edition", "nevertheless", "transport", "cited", "fees", "scope", "enhanced", "incorporated", "instructions", "subsidiary", "input", "abstract", "ministry", "capable", "expert", "preceding", "display", "incentive", "inhibition", "trace", "ignored", "incidence", "estate", "cooperative", "revealed", "index", "lecture", "discrimination", "overseas", "explicit", "aggregate", "gender", "underlying", "brief", "domain", "rational", "minimum", "interval", "neutral", "migration", "flexibility", "federal", "author", "initiatives", "allocation", "exceed",

"intervention", "confirmed", "definite", "classical", "chemical", "voluntary", "release", "visible", "finite", "publication", "channel", "file", "thesis", "equipment", "disposal", "solely", "deny", "identical", "submitted", "grade", "phenomenon", "paradigm", "ultimately", "extract", "survive", "converted", "transmission", "global", "inferred", "guarantee", "advocate", "dynamic", "simulation", "topic", "insert", "reverse", "decades", "comprise", "hierarchical", "unique", "comprehensive", "couple", "mode", "differentiation", "eliminate", "priority", "empirical", "ideology", "somewhat", "aid", "foundation", "adults", "adaptation", "quotation", "contrary", "media", "successive", "innovation", "prohibited", "isolated",

"highlighted", "eventually", "inspection", "termination", "displacement", "arbitrary", "reinforced", "denote", "offset", "exploitation", "detected", "abandon", "random", "revision", "virtually", "uniform", "predominantly", "thereby", "implicit", "tension", "ambiguous", "vehicle", "clarity", "conformity", "contemporary", "automatically", "accumulation", "appendix", "widespread", "infrastructure", "deviation", "fluctuations", "restore", "guidelines", "commodity", "minimises", "practitioners", "radical", "plus", "visual", "chart", "appreciation", "prospect", "dramatic", "contradiction", "currency", "inevitably", "complement", "accompany", "paragraph", "induced", "schedule", "intensity", "crucial", "via", "exhibit", "bias", "manipulation", "theme", "nuclear",

"bulk", "behalf", "unified", "commenced", "erosion", "anticipated", "minimal", "ceases", "vision", "mutual", "norms", "intermediate", "manual", "supplementary", "incompatible", "concurrent", "ethical", "preliminary", "integral", "conversely", "relaxed", "confined", "accommodation", "temporary", "distorted", "passive", "subordinate", "analogous", "military", "scenario", "revolution", "diminished", "coherence", "suspended", "mature", "assurance", "rigid", "controversy", "sphere", "mediation", "format", "trigger", "qualitative", "portion", "medium", "coincide", "violation", "device", "insights", "refine", "devoted", "team", "overlap", "attained", "restraints", "inherent", "route", "protocol", "founded", "duration",

"whereby", "inclination", "encountered", "convinced", "assembly", "albeit", "enormous", "reluctant", "posed", "persistent", "undergo", "notwithstanding", "straightforward", "panel", "odd", "intrinsic", "compiled", "adjacent", "integrity", "forthcoming", "conceived", "ongoing", "so-called", "likewise", "nonetheless", "levy", "invoked", "colleagues", "depression", "collapse"
);